name: scale7
recipe: drupal7
config:
  composer_version: "2.0.7"
  webroot: .
  xdebug: true
  database: mysql:8.0.22
  config:
    php: .lando.php.ini
    database: /dev/null
services:
  phpmyadmin:
    type: phpmyadmin
tooling:
  drush:
    service: appserver
    cmd: drush
    env:
      DRUSH_OPTIONS_URI: https://scale7.lndo.site
